import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { config } from '../config.js';
import { WallGoldClient, unwrapPrice } from '../wallgold/client.js';
import { TradingService } from '../services/trading-service.js';
import { analyzeEvidence } from '../domain/decision-engine.js';
import { technicalAnalysis } from '../domain/technical.js';
import { backtest } from '../domain/backtest.js';
import { store } from '../storage/json-store.js';
import { DEFAULT_POLICY } from '../domain/types.js';
import { evaluateWatchRules } from '../domain/monitoring.js';
import { round } from '../utils/math.js';
import { formatDecisionFa, faNumber } from '../utils/fa.js';
import { WALLGOLD_CARD_URI, wallgoldCardHtml } from '../ui/card.js';
import { signAnalysis, verifyAnalysis } from '../services/preview-token.js';

const txt=(structuredContent:any,text:string)=>({structuredContent,content:[{type:'text' as const,text}]});
const evidence=z.object({score:z.number().min(-100).max(100),confidence:z.number().min(0).max(100),freshnessMinutes:z.number().min(0),reasons:z.array(z.string()).min(1).max(8),sources:z.array(z.string()).max(12).optional()}).optional();

export function createServer(){
  const wallgold=new WallGoldClient(); const trading=new TradingService(wallgold);
  const server=new McpServer({name:'wallgold-copilot',version:'0.2.0'},{instructions:'این سرور برای تحلیل طلا و مدیریت تصمیم مالی به زبان فارسی است. هرگز از کاربر نخواه API Key وال‌گلد را داخل چت، ورودی ابزار یا Skill وارد کند و هیچ secret را در خروجی نشان نده. قبل از پیشنهاد، کیفیت و تازگی داده را بررسی کن؛ هیچ تحلیل را تضمین سود معرفی نکن. اجرای معامله در نسخه عمومی مجاز/فعال نیست. برای خرید یا فروش ابتدا تحلیل بازار، سپس پرتفوی و ریسک، و در اتصال خصوصی پیش‌نمایش تازه را بررسی کن.'});

  server.registerResource('wallgold-copilot-card',WALLGOLD_CARD_URI,{},async()=>({contents:[{uri:WALLGOLD_CARD_URI,mimeType:'text/html;profile=mcp-app',text:wallgoldCardHtml,_meta:{ui:{prefersBorder:true}}}]}));

  server.registerTool('get_wallgold_markets',{title:'دریافت بازارهای وال‌گلد',description:'بازارهای WallGold، وضعیت خرید/فروش، دقت، محدودیت مقدار/ارزش و ضرایب کارمزد را از پاسخ زنده بازار دریافت می‌کند.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async()=>{const r=await wallgold.getMarkets();return txt(r,`تعداد ${r.result?.length??0} بازار از WallGold دریافت شد؛ برای محدودیت سفارش همیشه همین پاسخ زنده را ملاک قرار بده.`)});

  server.registerTool('get_wallgold_api_key_setup_guide',{title:'راهنمای امن ساخت API Key وال‌گلد',description:'مراحل ساخت و ثبت امن API Key وال‌گلد را توضیح می‌دهد. این ابزار هیچ کلیدی دریافت، ذخیره یا نمایش نمی‌دهد.',inputSchema:{deployment:z.enum(['personal','multi_user']).default('personal')},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({deployment})=>{
    const personal=['در اپ/حساب WallGold وارد بخش «مدیریت API» شو.','برای کلید نام مشخص انتخاب کن و در صورت امکان IP عمومی خروجی سرور MCP را محدود کن.','مدت اعتبار ۳۰/۶۰/۹۰ روز را آگاهانه انتخاب کن و برای چرخش کلید قبل از انقضا یادآور عملیاتی داشته باش.','ساخت کلید را با کد پیامکی تأیید کن.','کلید فقط یک‌بار نمایش داده می‌شود؛ آن را در Secret Manager یا متغیر محیطی WALLGOLD_API_KEY ثبت کن.','API Key را هرگز در ChatGPT، Codex، پیام، Issue، لاگ یا ورودی ابزار paste نکن.'];
    const multi=['برای نسخه عمومی چندکاربره، از کاربران API Key، OTP یا رمز عبور خام نگیر.','ChatGPT/Codex باید با OAuth 2.1 به MCP شما متصل شوند و scopeها روی هر ابزار enforce شوند.','برای اتصال حساب واقعی WallGold، integration رسمی/تفویض دسترسی مورد توافق WallGold لازم است تا کاربر مجبور به ارسال API Key خام به Plugin نباشد.','تا قبل از فراهم‌شدن اتصال رسمی، قابلیت‌های وابسته به حساب را private/self-hosted نگه دار و نسخه عمومی را به داده‌های عمومی/تحلیل محدود کن.','ابزار اجرای معامله را در Plugin عمومی expose نکن؛ اجرای سرمایه‌گذاری فقط در اتصال خصوصی جدا بماند.'];
    const steps=deployment==='personal'?personal:multi;return txt({deployment,steps},steps.map((x,i)=>`${i+1}. ${x}`).join('\n'));
  });

  server.registerTool('check_wallgold_connection',{title:'بررسی اتصال وال‌گلد',description:'بدون نمایش secret، دسترسی بازار عمومی و در صورت تنظیم API Key دسترسی موجودی و قیمت خصوصی را بررسی می‌کند.',inputSchema:{symbol:z.string().default(config.wallgoldDefaultSymbol)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async({symbol})=>{
    const markets=await wallgold.getMarkets();
    if(!wallgold.hasApiKey()) return txt({publicApi:true,privateApi:false,marketCount:markets.result?.length??0,apiKeyConfigured:false},'بازار عمومی در دسترس است، اما API Key خصوصی WallGold روی سرور تنظیم نشده است.');
    const [balances,priceResponse]=await Promise.all([wallgold.getBalances(),wallgold.getPrivatePrice(symbol,'sell')]);
    const q=unwrapPrice(priceResponse);
    const result={publicApi:true,privateApi:true,marketCount:markets.result?.length??0,apiKeyConfigured:true,balanceCurrencies:balances.result.map((x:any)=>x.currency),priceToman:q.price,priceTtlSeconds:q.ttlSeconds??null,priceExpiresAt:q.priceExpiresAt??null};
    return txt(result,`اتصال خصوصی WallGold برقرار است. قیمت آزمایشی فروش دریافت شد و حدود ${q.ttlSeconds==null?'نامشخص':Math.floor(q.ttlSeconds)} ثانیه اعتبار دارد. هیچ کلیدی نمایش داده نشد.`);
  });

  server.registerTool('get_portfolio',{title:'مشاهده پرتفوی طلا',description:'موجودی کل، قفل‌شده و قابل‌استفاده تومان/طلا را از WallGold می‌خواند و با قیمت قابل فروش فعلی ارزش تقریبی و سهم طلا را محاسبه می‌کند.',inputSchema:{symbol:z.string().default(config.wallgoldDefaultSymbol)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async({symbol})=>{const r=await trading.portfolio(symbol);const p=r.portfolio;const lines=[`موجودی کل نقد: ${faNumber(p.cashToman,0)} تومان`,`نقد قفل‌شده: ${faNumber(p.lockedCashToman,0)} تومان`,`نقد قابل‌استفاده: ${faNumber(p.availableCashToman,0)} تومان`,`موجودی کل طلا: ${faNumber(p.goldGrams,3)} گرم`,`طلای قفل‌شده: ${faNumber(p.lockedGoldGrams,3)} گرم`,`طلای قابل‌استفاده: ${faNumber(p.availableGoldGrams,3)} گرم`,`ارزش تقریبی طلا: ${p.goldValueToman==null?'نامشخص':faNumber(p.goldValueToman,0)+' تومان'}`,`ارزش تقریبی کل: ${p.totalValueToman==null?'نامشخص':faNumber(p.totalValueToman,0)+' تومان'}`,`سهم طلا از دارایی: ${p.goldAllocationPct==null?'نامشخص':faNumber(p.goldAllocationPct,2)+'٪'}`,`قیمت مبنای فروش هر گرم: ${faNumber(r.liquidationPriceToman,0)} تومان`,`اعتبار قیمت: ${r.quoteTtlSeconds==null?'نامشخص':faNumber(Math.floor(r.quoteTtlSeconds),0)+' ثانیه'}`];return txt(r,lines.join('\n'))});
  server.registerTool('get_executable_quote',{title:'دریافت قیمت قابل معامله',description:'برای سمت خرید یا فروش قیمت اختصاصی کوتاه‌عمر را از WallGold می‌گیرد. گرفتن دوباره قیمت به معنی تمدید تضمینی همان پنجره اعتبار نیست؛ زمان انقضا/TTL پاسخ را ملاک قرار بده. این ابزار سفارش ثبت نمی‌کند.',inputSchema:{symbol:z.string().default(config.wallgoldDefaultSymbol),side:z.enum(['buy','sell'])},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async({symbol,side})=>{const raw=await wallgold.getPrivatePrice(symbol,side);const q=unwrapPrice(raw);const r={...raw,normalized:{priceToman:q.price,ttlSeconds:q.ttlSeconds??null,priceExpiresAt:q.priceExpiresAt??null,currentTime:q.currentTime??null}};return txt(r,[`قیمت قابل ${side==='buy'?'خرید':'فروش'}: ${faNumber(q.price,0)} تومان`,`زمان باقی‌مانده اعتبار: ${q.ttlSeconds==null?'نامشخص':faNumber(Math.floor(q.ttlSeconds),0)+' ثانیه'}`,`انقضای اعلام‌شده: ${q.priceExpiresAt??'نامشخص'}`].join('\n'))});
  server.registerTool('get_order_status',{title:'پیگیری وضعیت سفارش',description:'وضعیت یک سفارش موجود را با شناسه سفارش از WallGold می‌خواند.',inputSchema:{orderId:z.string().min(1)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async({orderId})=>{const r=await wallgold.getOrder(orderId);return txt(r,'وضعیت سفارش دریافت شد.')});

  server.registerTool('analyze_gold_market',{title:'تحلیل جامع بازار طلا',description:'شواهد طلای جهانی، دلار/ریال، تکنیکال، اقتصاد کلان، اخبار/ژئوپلیتیک و حباب داخلی را به یک تصمیم فارسی با امتیاز، درصد اطمینان و سناریوهای صعود/خنثی/نزول تبدیل می‌کند. درصد اطمینان از کیفیت، تازگی، پوشش و اختلاف شواهد محاسبه می‌شود و یک توکن امضاشده برای ذخیره امن همان نتیجه برمی‌گردد.',inputSchema:{globalGold:evidence,usdIrr:evidence,technical:evidence,macro:evidence,news:evidence,localPremium:evidence},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async(args)=>{const decision=analyzeEvidence(args as any);const r={...decision,analysisToken:signAnalysis(decision)};return txt(r,formatDecisionFa(decision))});

  server.registerTool('calculate_technical_indicators',{title:'محاسبه تحلیل تکنیکال',description:'از روی کندل‌های قیمت، شاخص قدرت نسبی، میانگین‌های متحرک نمایی، همگرایی و واگرایی میانگین‌ها، دامنه واقعی متوسط، حمایت و مقاومت را محاسبه و امتیاز تکنیکال -۱۰۰ تا +۱۰۰ تولید می‌کند.',inputSchema:{candles:z.array(z.object({time:z.string(),open:z.number(),high:z.number(),low:z.number(),close:z.number(),volume:z.number().optional()})).min(35).max(1000)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({candles})=>{const r=technicalAnalysis(candles);return txt(r,`امتیاز تکنیکال: ${r.score} از ۱۰۰.`)});

  server.registerTool('preview_trade',{title:'پیش‌نمایش خرید یا فروش طلا',description:'بدون ثبت سفارش، موجودی کل/قابل‌استفاده، قیمت واقعی کوتاه‌عمر، محدودیت زنده بازار، مقدار، مبلغ، ترکیب پرتفوی بعد و کنترل سیاست را محاسبه می‌کند. خروجی توکن کوتاه‌عمر برای درگاه اجرای خصوصی می‌دهد.',inputSchema:{side:z.enum(['buy','sell']),tomanAmount:z.number().positive().optional(),goldAmount:z.number().positive().optional(),symbol:z.string().optional()},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async(input)=>{if(!input.tomanAmount&&!input.goldAmount)throw new Error('یکی از «مبلغ تومان» یا «مقدار طلا» لازم است.'); const r=await trading.preview(input);const lines=[`نوع اقدام: ${r.sideFa}`,`مبلغ تقریبی: ${faNumber(r.notionalToman,0)} تومان`,`مقدار طلا: ${faNumber(r.goldAmountGrams,3)} گرم`,`قیمت هر گرم: ${faNumber(r.pricePerGramToman,0)} تومان`,`اعتبار قیمت: ${r.quoteTtlSeconds==null?'نامشخص':faNumber(Math.floor(r.quoteTtlSeconds),0)+' ثانیه'}`,`نقد کل قبل: ${faNumber(r.before.cashToman,0)} تومان`,`نقد قابل‌استفاده قبل: ${faNumber(r.before.availableCashToman,0)} تومان`,`نقد قابل‌استفاده بعد: ${faNumber(r.after.availableCashToman,0)} تومان`,`طلای کل قبل: ${faNumber(r.before.goldGrams,3)} گرم`,`طلای قابل‌استفاده قبل: ${faNumber(r.before.availableGoldGrams,3)} گرم`,`طلای قابل‌استفاده بعد: ${faNumber(r.after.availableGoldGrams,3)} گرم`,`سهم طلا بعد از اقدام: ${faNumber(r.after.goldAllocationPct,2)}٪`,`نتیجه کنترل ریسک و محدودیت بازار: ${r.risk.allowed?'مجاز':'مسدود'}`,`این فقط پیش‌نمایش است و هیچ سفارشی ثبت نشده است.`];if(r.risk.blocks?.length)lines.push('دلایل مسدودسازی:',...r.risk.blocks.map((x:string)=>`• ${x}`));if(r.risk.warnings?.length)lines.push('هشدارها:',...r.risk.warnings.map((x:string)=>`• ${x}`));return txt(r,lines.join('\n'))});

  server.registerTool('preview_rebalance',{title:'پیش‌نمایش بازمتعادل‌سازی پرتفوی',description:'ترکیب فعلی طلا/نقد را با هدف تخصیص مقایسه می‌کند و در صورت نیاز، بدون ثبت سفارش یک پیش‌نمایش خرید یا فروش برای نزدیک‌شدن به هدف می‌سازد.',inputSchema:{symbol:z.string().optional(),targetGoldAllocationPct:z.number().min(0).max(100).optional(),tolerancePct:z.number().min(0).max(20).default(0.5)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async(input)=>{const r=await trading.previewRebalance(input);return txt(r,r.messageFa)});

  server.registerTool('get_gold_cfo_brief',{title:'بریف مدیر هوشمند خزانه طلا',description:'یک نمای یکپارچه از پرتفوی WallGold، سیاست، آخرین تحلیل ذخیره‌شده و قوانین هشدار می‌سازد تا مشخص شود اقدام بعدی چیست. این ابزار معامله نمی‌کند.',inputSchema:{symbol:z.string().default(config.wallgoldDefaultSymbol)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async({symbol})=>{
    const [portfolio,policy,analysis,rules]=await Promise.all([trading.portfolio(symbol),store.getPolicy(),store.latestAnalysis(),store.listWatchRules()]);
    const brief={portfolio,policy,latestAnalysis:analysis,watchRules:rules,generatedAt:new Date().toISOString(),warningsFa:[...(analysis?[]:['هنوز تحلیل بازار ذخیره نشده؛ قبل از تصمیم خرید/فروش تحلیل تازه بساز.']),...(policy.mode==='advisor'?['سیاست در حالت مشاور است و اجرای معامله مجاز نیست.']:[])]};
    return txt(brief,analysis?`بریف خزانه آماده شد. آخرین تصمیم ذخیره‌شده: ${analysis?.decision?.signalFa??analysis?.decision?.summaryFa??'نامشخص'}.`:'بریف خزانه آماده شد؛ برای پیشنهاد معاملاتی ابتدا تحلیل تازه بازار لازم است.');
  });

  server.registerTool('render_analysis_card',{title:'نمایش کارت تحلیل بازار',description:'نتیجه نهایی ابزار تحلیل جامع بازار را به کارت فارسی قابل مشاهده تبدیل می‌کند. ابتدا تحلیل را انجام بده و سپس همان نتیجه را به این ابزار بده.',inputSchema:{decision:z.any()},outputSchema:{kind:z.literal('analysis'),data:z.any()},_meta:{ui:{resourceUri:WALLGOLD_CARD_URI}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({decision})=>({structuredContent:{kind:'analysis',data:decision},content:[{type:'text' as const,text:formatDecisionFa(decision)}]}));
  server.registerTool('render_trade_preview_card',{title:'نمایش کارت پیش‌نمایش معامله',description:'نتیجه نهایی پیش‌نمایش خرید یا فروش را به کارت فارسی تبدیل می‌کند. این ابزار هیچ سفارشی ثبت نمی‌کند.',inputSchema:{preview:z.any()},outputSchema:{kind:z.literal('preview'),data:z.any()},_meta:{ui:{resourceUri:WALLGOLD_CARD_URI}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({preview})=>({structuredContent:{kind:'preview',data:preview},content:[{type:'text' as const,text:'کارت پیش‌نمایش معامله آماده شد؛ هیچ سفارشی ثبت نشده است.'}]}));
  server.registerTool('render_treasury_card',{title:'نمایش کارت خزانه طلا',description:'نمای یکپارچه پرتفوی را به کارت فارسی تبدیل می‌کند. ابتدا اطلاعات پرتفوی یا بریف خزانه را دریافت کن.',inputSchema:{treasury:z.any()},outputSchema:{kind:z.literal('treasury'),data:z.any()},_meta:{ui:{resourceUri:WALLGOLD_CARD_URI}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({treasury})=>({structuredContent:{kind:'treasury',data:treasury},content:[{type:'text' as const,text:'کارت خزانه طلا آماده شد.'}]}));

  server.registerTool('get_treasury_policy',{title:'مشاهده سیاست مدیریت ریسک',description:'محدودیت‌ها و اهداف فعلی مدیریت سرمایه را می‌خواند.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>{const p=await store.getPolicy();return txt(p,'سیاست فعلی مدیریت ریسک دریافت شد.')});
  server.registerTool('set_treasury_policy',{title:'تنظیم سیاست مدیریت ریسک',description:'اهداف تخصیص دارایی و محدودیت‌های ریسک را در فضای خصوصی سرور ذخیره می‌کند؛ این ابزار هیچ معامله‌ای انجام نمی‌دهد.',inputSchema:{mode:z.enum(['advisor','copilot','autopilot']),minCashReserveToman:z.number().min(0),maxTradeToman:z.number().min(0),maxTradeGrams:z.number().min(0),maxDailyTrades:z.number().int().min(0),maxDailyNotionalToman:z.number().min(0),targetGoldAllocationPct:z.number().min(0).max(100),maxGoldAllocationPct:z.number().min(0).max(100),minConfidenceToBuy:z.number().min(0).max(100),minConfidenceToSell:z.number().min(0).max(100),maxQuoteAgeSeconds:z.number().int().min(1).max(600),requireAnalysisFreshMinutes:z.number().int().min(1).max(10080)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:true}},async(p)=>{const saved=await store.setPolicy({...DEFAULT_POLICY,...p});return txt(saved,'سیاست مدیریت ریسک ذخیره شد. این تغییر به‌تنهایی معامله‌ای اجرا نمی‌کند.')});

  server.registerTool('backtest_signal_strategy',{title:'بک‌تست استراتژی سیگنال',description:'روی تاریخچه قیمت و امتیاز سیگنال، استراتژی ساده ورود/خروج را بک‌تست می‌کند تا بازده، افت سرمایه و نرخ برد بررسی شود.',inputSchema:{points:z.array(z.object({time:z.string(),price:z.number().positive(),signalScore:z.number().min(-100).max(100)})).min(2).max(10000),initialCash:z.number().positive().default(100000000),buyThreshold:z.number().min(-100).max(100).default(35),sellThreshold:z.number().min(-100).max(100).default(-35)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async(a)=>{const r=backtest(a.points,a.initialCash,a.buyThreshold,a.sellThreshold);return txt(r,`بازده بک‌تست: ${r.returnPct}٪ | حداکثر افت: ${r.maxDrawdownPct}٪.`)});

  server.registerTool('save_analysis_snapshot',{title:'ثبت تصویر لحظه‌ای تحلیل',description:'فقط نتیجه امضاشده ابزار تحلیل جامع را برای تاریخچه تصمیم، ریسک و مانیتورینگ محلی ذخیره می‌کند. JSON دلخواه به‌عنوان تحلیل معتبر پذیرفته نمی‌شود و معامله‌ای انجام نمی‌دهد.',inputSchema:{analysisToken:z.string().min(20),note:z.string().max(1000).optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:false}},async({analysisToken,note})=>{const verified=verifyAnalysis(analysisToken);const row={id:crypto.randomUUID(),at:new Date(verified.createdAtMs).toISOString(),savedAt:new Date().toISOString(),decision:verified.decision,note};await store.addAnalysis(row);return txt({id:row.id,at:row.at,decision:row.decision,note:row.note??null},'نتیجه امضاشده Decision Engine ذخیره شد.')});
  server.registerTool('get_latest_analysis_snapshot',{title:'آخرین تصویر لحظه‌ای تحلیل',description:'آخرین تحلیل ذخیره‌شده را برای ادامه مانیتورینگ یا مقایسه می‌خواند.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>{const r=await store.latestAnalysis();return txt({analysis:r},r?'آخرین تحلیل بازیابی شد.':'هنوز تصویر لحظه‌ای تحلیلی ذخیره نشده است.')});

  server.registerTool('create_watch_rule',{title:'ساخت قانون هشدار',description:'یک قانون محلی برای هشدار قیمت/امتیاز تحلیل ذخیره می‌کند؛ این ابزار معامله نمی‌کند و اعلان بیرونی ارسال نمی‌کند.',inputSchema:{name:z.string().min(1).max(100),kind:z.enum(['price_below','price_above','signal_score_above','signal_score_below']),threshold:z.number(),enabled:z.boolean().default(true)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:false}},async(r)=>{const row={id:crypto.randomUUID(),createdAt:new Date().toISOString(),...r};await store.addWatchRule(row);return txt(row,'قانون هشدار ذخیره شد.')});
  server.registerTool('list_watch_rules',{title:'فهرست قوانین هشدار',description:'قوانین هشدار ذخیره‌شده را می‌خواند.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>{const rules=await store.listWatchRules();return txt({rules},`${rules.length} قانون هشدار وجود دارد.`)});

  server.registerTool('create_treasury_plan',{title:'ساخت برنامه خزانه‌داری',description:'یک برنامه خرید دوره‌ای، بازمتعادل‌سازی یا شرطی را برای اجرای دوره‌ای توسط هماهنگ‌کننده ذخیره می‌کند. این ابزار فقط برنامه را ثبت می‌کند و معامله‌ای انجام نمی‌دهد.',inputSchema:{name:z.string().min(1).max(120),kind:z.enum(['dca','rebalance','price_condition','signal_condition']),enabled:z.boolean().default(true),everyDays:z.number().int().min(1).max(365).optional(),tomanAmount:z.number().positive().optional(),targetGoldAllocationPct:z.number().min(0).max(100).optional(),condition:z.object({operator:z.enum(['gt','gte','lt','lte']),value:z.number()}).optional(),minConfidence:z.number().min(0).max(100).optional(),notes:z.string().max(1000).optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:false}},async(plan)=>{const row={id:crypto.randomUUID(),createdAt:new Date().toISOString(),lastEvaluatedAt:null,...plan};await store.addTreasuryPlan(row);return txt(row,'برنامه خزانه‌داری ذخیره شد؛ برای اجرای خودکار باید زمان‌بند خصوصی آن را ارزیابی کند و هیچ معامله‌ای در این مرحله انجام نشد.')});
  server.registerTool('list_treasury_plans',{title:'فهرست برنامه‌های خزانه‌داری',description:'برنامه‌های خرید دوره‌ای، بازمتعادل‌سازی و قوانین شرطی ذخیره‌شده را می‌خواند.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>{const plans=await store.listTreasuryPlans();return txt({plans},`${plans.length} برنامه خزانه‌داری ذخیره شده است.`)});

  server.registerTool('record_market_snapshot',{title:'ثبت تصویر لحظه‌ای بازار WallGold',description:'قیمت قابل خرید و فروش فعلی WallGold را همراه با اختلاف قیمت خرید و فروش و اطلاعات بازار در تاریخچه محلی ذخیره می‌کند تا به‌مرور دیتاست بک‌تست و کیفیت اجرا ساخته شود.',inputSchema:{symbol:z.string().default(config.wallgoldDefaultSymbol)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true,idempotentHint:false}},async({symbol})=>{
    const [markets,buyResponse,sellResponse]=await Promise.all([wallgold.getMarkets(),wallgold.getPrivatePrice(symbol,'buy'),wallgold.getPrivatePrice(symbol,'sell')]);
    const buy=unwrapPrice(buyResponse),sell=unwrapPrice(sellResponse);
    const spreadToman=round(buy.price-sell.price,0);
    const spreadPct=sell.price>0?round((buy.price-sell.price)/sell.price*100,4):null;
    const market=markets.result.find((x:any)=>x.symbol===symbol)??null;
    const row={id:crypto.randomUUID(),at:new Date().toISOString(),symbol,buyPriceToman:buy.price,sellPriceToman:sell.price,spreadToman,spreadPct,buyExpiresAt:buy.priceExpiresAt??null,sellExpiresAt:sell.priceExpiresAt??null,market};
    await store.addMarketSnapshot(row); return txt(row,'تصویر لحظه‌ای بازار WallGold ثبت شد.');
  });
  server.registerTool('list_market_snapshots',{title:'تاریخچه تصاویر لحظه‌ای بازار',description:'تصاویر لحظه‌ای محلی قیمت خرید/فروش WallGold را برای تحلیل اختلاف قیمت خرید و فروش، بک‌تست و کیفیت اجرا می‌خواند.',inputSchema:{limit:z.number().int().min(1).max(10000).default(500)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({limit})=>{const snapshots=await store.listMarketSnapshots(limit);return txt({snapshots},`${snapshots.length} تصویر لحظه‌ای بازار بازیابی شد.`)});

  server.registerTool('evaluate_watch_rules',{title:'ارزیابی قوانین هشدار',description:'قوانین هشدار ذخیره‌شده را با قیمت فعلی WallGold و/یا امتیاز آخرین تحلیل بررسی می‌کند و قوانین فعال‌شده را برمی‌گرداند. اعلان بیرونی یا معامله انجام نمی‌دهد.',inputSchema:{symbol:z.string().default(config.wallgoldDefaultSymbol),priceToman:z.number().positive().optional(),signalScore:z.number().min(-100).max(100).optional()},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},async({symbol,priceToman,signalScore})=>{
    let price=priceToman; let score=signalScore;
    if(price==null){const q=unwrapPrice(await wallgold.getPrivatePrice(symbol,'sell'));price=q.price;}
    if(score==null){const a=await store.latestAnalysis();score=Number(a?.decision?.score);if(!Number.isFinite(score))score=undefined;}
    const rules=await store.listWatchRules();const evaluations=evaluateWatchRules(rules,{priceToman:price,signalScore:score});const triggered=evaluations.filter((x:any)=>x.matched);
    return txt({priceToman:price,signalScore:score??null,evaluations,triggered},triggered.length?`${triggered.length} قانون هشدار فعال شده است.`:'هیچ قانون هشداری در شرایط فعلی فعال نشده است.');
  });

  server.registerTool('record_shadow_trade',{title:'ثبت معامله آزمایشی',description:'یک معامله فرضی را برای معامله آزمایشی ثبت می‌کند؛ هیچ درخواست معامله‌ای به WallGold ارسال نمی‌شود.',inputSchema:{side:z.enum(['buy','sell']),grams:z.number().positive(),priceToman:z.number().positive(),reason:z.string().max(1000),signalScore:z.number().min(-100).max(100),confidence:z.number().min(0).max(100)},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:false}},async(x)=>{const row={id:crypto.randomUUID(),at:new Date().toISOString(),...x};await store.addShadowTrade(row);return txt(row,'معامله آزمایشی ثبت شد؛ سفارش واقعی وجود ندارد.')});
  server.registerTool('list_shadow_trades',{title:'گزارش معاملات آزمایشی',description:'معاملات آزمایشی ثبت‌شده را برای ارزیابی عملکرد می‌خواند.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>{const trades=await store.listShadowTrades();return txt({trades},`${trades.length} معامله آزمایشی ثبت شده است.`)});

  // This tool is intentionally NOT registered in the public/default configuration.
  // OpenAI's public plugin guidelines prohibit execution of investment trades.
  if(config.allowMcpTradeExecution){
    server.registerTool('execute_private_trade',{title:'اجرای خصوصی معامله',description:'فقط برای اتصال خصوصی و غیرقابل‌انتشار: یک توکن پیش‌نمایش معتبر را پس از دریافت قیمت قابل معامله تازه و کنترل سقف‌های سرور به سفارش WallGold تبدیل می‌کند.',inputSchema:{previewToken:z.string().min(20)},annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true,idempotentHint:false}},async({previewToken})=>{const r=await trading.executePrivate(previewToken);return txt(r,r.messageFa??'درخواست اجرای خصوصی پردازش شد؛ نتیجه تطبیق سفارش را بررسی کن.')});
  }
  return server;
}
